Repository ucsb-cs156-f24/proj-rec-f24-08, pull requests merged in 2024-11, with the labels that each got.

#35 Mike - E11-B1: Create rec req table
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
  src/main/resources/db/migration/changes/RecommendationRequest.json
Labels: Ready-For-Staff

#38 AW-Epic14-F1: Added placeholders for professor pages
  frontend/src/App.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/Requests/CompletedRequestsPage.js
  frontend/src/main/pages/Requests/PendingRequestsPage.js
  frontend/src/main/pages/Requests/StatisticsPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/Requests/CompletedRequestsPage.test.js
  frontend/src/tests/pages/Requests/PendingRequestsPage.test.js
  frontend/src/tests/pages/Requests/StatisticsPage.test.js
Labels: F24, 10

#56 Feature 10 - B1: Request Type Table
  src/main/java/edu/ucsb/cs156/rec/entities/RequestType.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RequestTypeRepository.java
  src/main/resources/db/migration/changes/RequestType.json
Labels: F24, 5, Merge Candidate-CI

#58 divyani - Added Utils and Utils tests for Recommendation Request.
  frontend/src/main/utils/RecommendationRequestUtils.js
  frontend/src/tests/utils/RecommendationRequestUtils.test.js
Labels: F24, 5, Merge Candidate-CI

#62 Oscar - Eliminates Frontend for Restaurants, UCSBDates, Placeholders (Redo of old PR branched directly from main)
  frontend/src/App.js
  frontend/src/fixtures/restaurantFixtures.js
  frontend/src/fixtures/ucsbDatesFixtures.js
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/components/Restaurants/RestaurantForm.js
  frontend/src/main/components/Restaurants/RestaurantTable.js
  frontend/src/main/components/UCSBDates/UCSBDateForm.js
  frontend/src/main/components/UCSBDates/UCSBDatesTable.js
  frontend/src/main/pages/Placeholder/PlaceholderCreatePage.js
  frontend/src/main/pages/Placeholder/PlaceholderEditPage.js
  frontend/src/main/pages/Placeholder/PlaceholderIndexPage.js
  frontend/src/main/pages/Restaurants/RestaurantCreatePage.js
  frontend/src/main/pages/Restaurants/RestaurantEditPage.js
  frontend/src/main/pages/Restaurants/RestaurantIndexPage.js
  frontend/src/main/pages/UCSBDates/UCSBDatesCreatePage.js
  frontend/src/main/pages/UCSBDates/UCSBDatesEditPage.js
  frontend/src/main/pages/UCSBDates/UCSBDatesIndexPage.js
  frontend/src/main/utils/UCSBDateUtils.js
  frontend/src/main/utils/restaurantUtils.js
  frontend/src/stories/components/Restaurants/RestaurantForm.stories.js
  frontend/src/stories/components/Restaurants/RestaurantTable.stories.js
  frontend/src/stories/components/UCSBDates/UCSBDateForm.stories.js
  frontend/src/stories/components/UCSBDates/UCSBDatesTable.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantCreatePage.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantEditPage.stories.js
  frontend/src/stories/pages/Restaurants/RestaurantIndexPage.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesCreatePage.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesEditPage.stories.js
  frontend/src/stories/pages/UCSBDates/UCSBDatesIndexPage.stories.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/components/Restaurants/RestaurantForm.test.js
  frontend/src/tests/components/Restaurants/RestaurantTable.test.js
  frontend/src/tests/components/UCSBDates/UCSBDateForm.test.js
  frontend/src/tests/components/UCSBDates/UCSBDatesTable.test.js
  frontend/src/tests/pages/Placeholder/PlaceholderCreatePage.test.js
  frontend/src/tests/pages/Placeholder/PlaceholderEditPage.test.js
  frontend/src/tests/pages/Placeholder/PlaceholderIndexPage.test.js
  frontend/src/tests/pages/Restaurants/RestaurantCreatePage.test.js
  frontend/src/tests/pages/Restaurants/RestaurantEditPage.test.js
  frontend/src/tests/pages/Restaurants/RestaurantIndexPage.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesCreatePage.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesEditPage.test.js
  frontend/src/tests/pages/UCSBDates/UCSBDatesIndexPage.test.js
  frontend/src/tests/utils/UCSBDateUtils.test.js
  frontend/src/tests/utils/useBackend.test.js
Labels: F24, 5

#48 Oscar - Creates Fixtures for Recommendation Requests (Updated to reflect new controller)
  frontend/src/fixtures/recommendationRequestFixtures.js
Labels: F24, 5

#60 Caleb-Add roles for Professor and Student (precursor to F12 and Epic14-B1) + TESTS
  frontend/src/fixtures/usersFixtures.js
  src/main/java/edu/ucsb/cs156/rec/config/SecurityConfig.java
  src/main/java/edu/ucsb/cs156/rec/entities/User.java
  src/main/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptor.java
  src/main/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptorConfig.java
  src/main/resources/db/migration/changes/Users.json
  src/test/java/edu/ucsb/cs156/rec/interceptors/RoleInterceptorTests.java
Labels: 20, Merge Candidate-CI

#70 Caleb - Update User Controllers and User Table so Admins can toggle roles of different users for Professor, Students, Admins (plus tests)
  frontend/src/main/components/Users/UsersTable.js
  frontend/src/tests/components/Users/UsersTable.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/UsersController.java
  src/main/resources/db/migration/changes/Users.json
  src/test/java/edu/ucsb/cs156/rec/controllers/UsersControllerTests.java
Labels: F24, 10

#55 divyani - Added table component (plus tests and stories) for RecommendationRequest.
  frontend/src/fixtures/recommendationRequestFixtures.js
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/stories/components/RecommendationRequest/RecommendationRequestTable.stories.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
  frontend/src/tests/utils/RecommendationRequestUtils.test.js
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
Labels: F24, Ready-For-Staff

#66 Oscar - GET and POST routes for RecommendationRequest, database changes
  src/main/java/edu/ucsb/cs156/rec/ExampleApplication.java
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
  src/main/resources/db/migration/changelog-master.json
  src/main/resources/db/migration/changes/RecommendationRequest.json
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestTests.java
  src/test/java/edu/ucsb/cs156/rec/testconfig/TestConfig.java
Labels: F24, 10, Merge Candidate-CI

#76 Mike - Feature 10 - B2: Request Type CRUD operations
  src/main/java/edu/ucsb/cs156/rec/controllers/ApiController.java
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypeController.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypeControllerTests.java
Labels: 10, Ready-For-Staff, Merge Candidate-CI

#68 divyani - Added DELETE and PUT operations (plus tests) for RecommendationRequest
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
  src/main/java/edu/ucsb/cs156/rec/repositories/UserRepository.java
  src/test/java/edu/ucsb/cs156/rec/ControllerTestCase.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestControllerTest.java
  src/test/java/edu/ucsb/cs156/rec/testconfig/TestConfig.java
Labels: F24, 10, Merge Candidate-CI

#72 Oscar - Form Component for Recommendation Requests (redo of old PR after controller changes)
  frontend/src/fixtures/recommendationRequestFixtures.js
  frontend/src/fixtures/recommendationTypeFixtures.js
  frontend/src/fixtures/usersFixtures.js
  frontend/src/main/components/RecommendationRequest/RecommendationRequestForm.js
  frontend/src/stories/components/RecommendationRequest/RecommendationRequestForm.stories.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestForm.test.js
  src/main/java/edu/ucsb/cs156/rec/controllers/RequestTypeController.java
  src/main/java/edu/ucsb/cs156/rec/controllers/UsersController.java
  src/main/java/edu/ucsb/cs156/rec/entities/RecommendationRequest.java
  src/main/java/edu/ucsb/cs156/rec/repositories/UserRepository.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RequestTypeControllerTests.java
  src/test/java/edu/ucsb/cs156/rec/controllers/UsersControllerTests.java
Labels: F24, 10, Ready-For-Staff, Merge Candidate-CI

#77 AW- E14:Added a filterByStatus method for professor
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RecommendationRequestRepository.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestTests.java
Labels: F24, 10, Ready-For-Staff, Merge Candidate-CI

#80 divyani - Corrections to Table and Table Tests for Recommendation Requests
  frontend/src/main/components/RecommendationRequest/RecommendationRequestTable.js
  frontend/src/tests/components/RecommendationRequest/RecommendationRequestTable.test.js
Labels: F24, 5, Ready-For-Staff, Merge Candidate-CI

#79 Oscar - POST Change to check recommendation types against database
  src/main/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestController.java
  src/main/java/edu/ucsb/cs156/rec/repositories/RequestTypeRepository.java
  src/test/java/edu/ucsb/cs156/rec/controllers/RecommendationRequestTests.java
Labels: F24, 5, Ready-For-Staff, Merge Candidate-CI
